project_id = "bdetejjahokasedpghlp"

[functions.google-sheets]
verify_jwt = false

[functions.auth]
verify_jwt = false

[functions.data-operations]
verify_jwt = false

[functions.solicitacoes-codigo]
verify_jwt = false